#!/bin/sh
ifconfig eth0 192.168.1.17
mount -t nfs -o nolock 192.168.1.102:/work/nfs_root /mnt
mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
mount -a
exec /etc/rc.local
